stages:
- name: 制作镜像
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: mike/nginx
- name: 运行
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
