stages:
- name: 制作镜像
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: mike/nginx/${CICD_GIT_BRANCH}:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 127.0.0.1:34933
- name: 运行
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
