stages:
- name: 制作镜像
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: zhaoming23/nginx:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: "index.docker.io/v1"
- name: 运行
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
