stages:
- name: 制作镜像
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ${CICD_LOCAL_REGISTRY}/mike/nginx/${CICD_GIT_BRANCH}:${CICD_EXECUTION_SEQUENCE}
- name: 运行
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
